apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: orbo-mate
build:
  platforms: ["linux/amd64", "linux/arm64"]
  artifacts:
    - image: orbo-mate
      docker:
        dockerfile: Dockerfile
test:
  - image: orbo-mate
    structureTests:
      - structure-tests.yaml
manifests:
  kustomize:
    paths:
      - k8s/base
deploy:
  kubectl: {}
profiles:
  - name: local
    manifests:
      kustomize:
        paths:
          - k8s/overlays/local
