apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orbo-mate
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shipperizer/orbo-mate.git'
    targetRevision: HEAD
    path: k8s/overlays/argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: orbo-mate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
